### ISSUE TITLE
Packagist release?

### ISSUE THREAD

**Issue by DavertMik** [bookitcom/codeception-testrail#1]
Hi, thanks for the extension.

What is current state of it? I didn't find it on packagist :( Also once it is ready please add it to our Addons section on Codeception website

**Comment by DavertMik** [comment]
Also if you will publish it that would be cool if you remove hardcoded URL https://github.com/bookitcom/codeception-testrail/blob/master/src/Extension.php#L279

And add some installation instructions.

**Comment by randlem** [comment]
Thanks for pointing that out.  I'll get that cleaned up.
